title: Jini
description: Less rework. Faster handoffs. Clear next steps.
theme: jekyll-theme-primer
url: https://maridlabsai.github.io
baseurl: /jini
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
