title: Jini
description: The framework for week two of work.
theme: jekyll-theme-primer
url: https://maridlabsai.github.io
baseurl: /jini
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
